### ISSUE TITLE
Suggest Enhancement 

### ISSUE THREAD

**Issue by yousef-soliman** [amrsalama/online-judges-scraper#7]
base on my little experience in javascript, i wanna suggest:
make A class that will be Parent for CodeForces, UVa, URI classes, so it will be easy to add a new website without many changes, and it will help there 
```
if (codeforces) {
        logins.push(Codeforces.login(this._browser, codeforces.credentials));
      }
if (uva) {
        logins.push(UVa.login(this._browser, uva.credentials));
}
if (uri) {
        logins.push(URI.login(this._browser, uri.credentials));
     }
```

with array of parent type(contains subclasses) and foreach with the same call function
if i missed something related to typescript please guide me.

**Comment by amrsalama** [comment]
@yousef-soliman @kerolloz come on guys, I swear I'm still putting basic headlines 😂

**Comment by kerolloz** [comment]
@amrsalama 😂 same suggestion 😂❤️

**Comment by amrsalama** [comment]
@yousef-soliman Welcome back ❤️

**Comment by yousef-soliman** [comment]
@amrsalama I am very excited to work with you again ❤, let's do it

**Comment by KerollosNabil** [comment]
@amrsalama hya de ely kant btdrb fe elcontest 😁😁🤔🤔🤔🤔

**Comment by Mohamed-Fakhry** [comment]
@amrsalama kant sa3'ala ezay 😁😁
